name: task_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.4
  dio: ^5.3.3
  dartz: ^0.10.1
  intl:
  lottie:
  internet_connection_checker: ^1.0.0+1
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  flutter_svg:
  page_transition: ^2.1.0
  flutter_staggered_grid_view: ^0.4.0
  cached_network_image:
  shimmer:
  sqflite: ^2.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21



flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/